name: Auto-update Devlog on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-devlog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Generate devlog
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python scripts/generate_devlog.py

      - name: Commit and push changes
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config user.name "seung-gu"
          git config user.email "seunggu.kang.kr@gmail.com"
          git remote set-url origin https://x-access-token:${PERSONAL_TOKEN}@github.com/${{ github.repository }}
          git add docs/devlog.md
          git commit -m "🔄 Auto-update devlog" || echo "No changes"
          git push origin HEAD:main
