name: Update Devlog on Push

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  update-devlog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Echo token (masked)
        run: echo "TOKEN=${{ secrets.PERSONAL_TOKEN }}"

      - name: Install dependencies
        run: pip install python-dotenv requests

      - name: Check if only devlog.md changed
        id: changes
        uses: tj-actions/changed-files@v44
        with:
          files: docs/devlog.md

      - name: Skip devlog generation if only devlog.md changed
        if: steps.changes.outputs.only_changed == 'true'
        run: echo "🟡 Only devlog.md changed. Skipping generate_log.py."

      - name: Run Log Generator
        run: python logging/generate_log.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PYTHONPATH: ${{ github.workspace }}

      - name: Commit and Push Devlog
        run: |
          git config user.name "seung-gu"
          git config user.email "seunggu.kang.kr@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/${{ github.repository }}
          git add docs/doclog.md
          git commit -m "🔄 Auto-update doclog" || echo "No changes"
          git push origin HEAD
