name: Auto-update Devlog on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-devlog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Generate devlog
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python scripts/generate_devlog.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/devlog.md
          git commit -m "🔄 Update devlog (auto)" || echo "No changes"
          git push
